name       : nasc
version    : 0.5.4
release    : 18
source     :
    - https://github.com/parnold-x/nasc/archive/0.5.4.tar.gz : eba0d00d33dba7fc7a93b55d16ef769fe87839c9660d2a43e28e7fdd37a7cff5
license    : GPL-3.0-or-later
component  : office.maths
libsplit   : no
summary    : NaSC is an app where you do math like a normal person.
description: |
    It’s an app where you do math like a normal person. It lets you type whatever you want and smartly figures out what is math and spits out an answer on the right pane.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libqalculate)
    - pkgconfig(libsoup-2.4)
    - cln-devel
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-compile-icon-cache.patch
    %cmake -DGSETTINGS_COMPILE=OFF .
build      : |
    %make
install    : |
    %make_install
