name       : nasc
version    : 0.8.0
release    : 34
source     :
    - git|https://github.com/parnold-x/nasc : 0.8.0
license    : GPL-3.0-or-later
component  : office.maths
libsplit   : no
summary    : NaSC is an app where you do math like a normal person
description: |
    It’s an app where you do math like a normal person. It lets you type whatever you want and smartly figures out what is math and spits out an answer on the right pane.
builddeps  :
    - pkgconfig(granite)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(libqalculate)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-4.0)
    - cln-devel
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
